# Permalinks
permalink:           pretty

# Setup
title:               Marks's Blog
tagline:             'Meine Ergüsse'
description:         'Disclaimer! Wenn ihr Grammar Nazis seit, euch bei Rechtschreibfehlern der Hut hoch geht oder ihr kein Bock habt wirre Sätze zu entschüsseln. Dann seit ihr hier nicht Richtig, außer ihr stellt korregierende Merge Request'
url:                 http://www.nitrust.de
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Eisenblaetter
  url:               https://twitter.com/qeqar

exclude: [vendor]

# Custom vars
version:             1.0.0
